var gulp = require('gulp');
var $ = require('gulp-load-plugins')();
var path = require('path');
var del = require('del');
var _ = require('lodash');
var webpack = require('webpack');
var swallowError = require('./helpers/swallow-error');
var config = require('./config/scripts');

/**
 * create a single instance of the compiler to allow caching.
 *
 * @type {Webpack}
 */
var compiler = $.util.env.production ? webpack(_.extend(config.baseConfig, config.productionConfig))
                                     : webpack(config.baseConfig);

/**
 * Compile js files.
 *
 * Options:
 *   --production: Optimize final js.
 */
gulp.task('scripts', function (done) {
  compiler.run(function (err, stats) {
    if (err) {
      throw new $.util.PluginError('scripts', err);
    }

    $.util.log('[scripts]', stats.toString({ colors: true }));

    done();
  });
});

/**
 * Compile js files with watch mode.
 */
gulp.task('scripts:watch', ['scripts'], function () {
  gulp.watch('./scripts/**/*.js', ['scripts']);
});

/**
 * Clean up js files generated by gulp.
 */
gulp.task('scripts:clean', function (done) {
  del(['./public/js/*.js'], done);
});
