var gulp = require('gulp');
var del = require('del');
var stylesBuilder = require('./helpers/stylesBuilder');
var config = require('./config/styles');

/**
 * Compile less files
 *
 * Options:
 *   --production: Optimize final css.
 */
gulp.task('styles', function () {
  return stylesBuilder();
});

/**
 * Watch file change event on save and compile css file.
 */
gulp.task('styles:watch', ['styles'], function () {
  gulp.watch(config.watchFiles, ['styles']);
});

/**
 * Clean up css files generated by gulp.
 */
gulp.task('styles:clean', function (done) {
  del([config.dest + '*.css'], done);
});
